### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by matt-psaltis** [VahidN/EFCoreSecondLevelCacheInterceptor#133]
Hi there!

Cool library. I was wondering how transactions affect the query cache - Do query results get cached immediately or only after successful transaction commit. Wondering if it introduces dirty reads and/or phantom reads.

**Comment by VahidN** [comment]
[It there is an "insert ", "update ", "delete " or "create " in your intercepted query](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor#3--setting-up-the-cache-invalidation), the related cache item will be invalidated automatically.

**Comment by BabellDev** [comment]
What about the following scenario?

```
using(var txn = new dbContext.Database.BeginTransaction())
{
   // Read and modify an entity
   var entity = dbContext.SomeEntities.First();
   entity.Name = "FOO";

   // Save the change, cache will be invalidated
   dbContext.SaveChanges();

   // Read the same entity, this will get cached with name "FOO"
   entity = dbContext.SomeEntities.First();

   // Call some method
   // THIS METHOD THROWS AN EXCEPTION SO THE TRANSACTION IS NEVER COMMITTED
   DoSomeWork(entity);

   // (we never hit these lines, so the cache is not invalidated and the transaction is not committed)
   dbContext.SaveChanges();
   txn.Commit();
}
```

Unless I am mistaken, the entity will now be cached with name "FOO", which is incorrect since that change was never actually committed to the database.

**Comment by VahidN** [comment]
`which is incorrect `
Why? There's no harm in it, because it's a reflection of your actual db. Next time you call `dbContext.SomeEntities.First()`, it will be faster.

**Comment by BabellDev** [comment]
In my sample code that change to "FOO" would never be committed to the physical database because the transaction was never committed, so the cached version would be out of sync with the database

**Comment by VahidN** [comment]
It's not.

**Comment by BabellDev** [comment]
The name "FOO" will not be in the cache?  Note that this change would only be written to the database if the transaction is successfully committed, but because DoSomeWork() throws an exception, we never commit the transaction so the name of "FOO" is not written to the DB (the transaction will roll back).

**Comment by VahidN** [comment]
`dbContext.SomeEntities.First()` will call your db, not your in-memory context. It's not a LINQ to Objects query.

**Comment by BabellDev** [comment]
Inside the transaction when I call `dbContext.SomeEntities.First() `it will return the entity with name "FOO", even though it is not physically committed to the database yet.  It will only get physically written to the database when the transaction is committed, but inside the transaction EF will still return the pending state.

**Comment by BabellDev** [comment]
To demonstrate the issue, assume this.context.SomeEntities.First() returns an entity with name "BAR"

```
            using (var txn = this.context.BeginTransaction())
            {
                // query, modify, and save
                var temp = this.context.SomeEntities.First();
                temp.Name = "FOO";
                this.context.SaveChanges();

               // query again
               temp = this.context.SomeEntities.First();

                // Do not commit txn
            }
```

Without caching enabled, in a subsequent request when I call `this.context.SomeEntities.First()` I get entity with name "BAR" (correct - matches physical DB).  

With caching enabled, in a subsequent request when I call `this.context.SomeEntities.First()` I get entity with name "FOO" (incorrect - does not match physical DB).

This is indeed a great library btw!  Just a nuance we need to watch out for.

**Comment by BabellDev** [comment]
To work around this issue in our project, we simply suppress caching when there is an open transaction.  For us, missing out on some caching is less severe than having cached data which is out of sync. 

To accomplish this we have implemented an interceptor which wraps the SecondLevelCacheInterceptor and only invokes it when `command.Transaction` is null, otherwise we call down to the base. 

I have attached the sample code for others who would like to take a similar approach.
[TransactionFixInterceptor.txt](https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/files/7086658/TransactionFixInterceptor.txt)
