### ISSUE TITLE
cache suitable for joins?

### ISSUE THREAD

**Issue by namnik** [VahidN/EFCoreSecondLevelCacheInterceptor#28]
Hi,
I have some big data that rarely change. for example 'Divisions of provinces and cities'.
but this tables always used in the join with some other tables. now how I can used my table cache in Join, include() ?

thanks

**Comment by VahidN** [comment]
This interceptor will receive the whole SQL query with all of its parameters and then makes a hash-key out of these info. After that its result will be cached. Now the join means having dependencies to the other tables and yes, these queries will be watched and the cache will be invalidated if a dependency is involved in a CRUD operation automatically. So apply the `Cachable()` method to your LINQ query (it doesn't matter how you are going to write it, because the final SQL query will be watched here, not your LINQ expression) normally.

**Comment by namnik** [comment]
ببخشید مجبور شدم برای بیان منظورم فارسی بنویسم.
سناریوی من
یک بار میرم از جدول لیست تقسیمات کشوری رو میارم تو کش شامل تمام استانها و شهرستان ها و روستاها 
حال این تقسمات کشوری در ده جای مختلف با جداول مختلف در لاجیکهای مختلف جوین میخوره...
سوال من اینه که کش کلی جدول تفسمات کشوری الان به نظر به درد نخوره ؟
چونکه  هر بار تو سناریوهای مختلف اون جوین تو دیبی میخوره و اصلا از کش استفاده نمیشه و الکیه کش
من نمیخوام کل کوئری که فقط یه طرفش جدول تقسیمات کشوریه کش بشه... فقط جدول تقسیمات کش بشه

**Comment by VahidN** [comment]
<div dir="rtl">

اين كتابخانه دو حالت كش تمام كوئري‌ها و كش يك تك كوئري مشخص را دارد. حالت دوم را استفاده كنيد

**Comment by namnik** [comment]
اینکه فرمودید بدیهیاتِ این پکیجه ولی فک کنم مشکل نوع بیان من بود 
سناریو
  من یه بار کل جدول تقسیمات کشوری رو میارم تو کش... بعدش این جدول در سرویسهای مختلف با جداول دیگر جوینهای مختلف میخوره... اینجا ای اِف برای جوین با تقسیمات دوباره میره سراغ دیبی و هیج رجوعی به کش تقسیمات نمیکنه و در نتیجه الکی تقسمات رو آوردم تو کش... چونکه هیچوقت خودش مستقل استفاده نمیشه و همیشه طی جوین با جداول دیگه استفاده میشه
برای این حالت راه حلی هست؟

**Comment by VahidN** [comment]
خير قربان. اين كش يك كوئري كامل هست. براي شما مناسب نيست از آن استفاده نكنيد
