### ISSUE TITLE
Cached item conflict with change tracker. 

### ISSUE THREAD

**Issue by grinay** [VahidN/EFCoreSecondLevelCacheInterceptor#39]
Hello. Face into an issue. Was investigate and found steps to reproduce.
# Summary of the issue

Simple test to reproduce with any entity:

```
            var dbContext = ServiceProvider.GetRequiredService<DbContext>();
          
            await dbContext.Tags.AddAsync(new Tag()
            {
                Code = "123"
            });
            await dbContext.SaveChangesAsync();
          
            var tag = await dbContext.Tags.Cacheable().FirstOrDefaultAsync(x => x.Code == "123");
            dbContext.Attach(tag);
```

And you will get 

The instance of entity type 'Tag' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

If you remove Cachable() change tracker attach item without any problem.

**Comment by grinay** [comment]
Hm. This issue related to not tracked items. No cachable itself.

**Comment by VahidN** [comment]
Because this how the 2nd level caching works:
1st call: read from the database -> LINQ to entities
2nd call: read from the cache -> LINQ to objects
.
.
.
nth call: read from the cache -> LINQ to objects

You should use it for reporting scenarios only. For the 1st time it will be retrieved from the context, for 2nd time, it will be retrieved from the cache directlty. that's why it can't be tracked and it shouldn't be tracked.

**Comment by grinay** [comment]
Ok. Thanks.
